# Generated by Django 4.1 on 2023-01-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=8, unique=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('withdraw_no', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('disprition', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staf.accountdetails')),
            ],
        ),
    ]
