# Generated by Django 4.1 on 2023-01-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coustuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='disprition',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_type',
        ),
    ]
