# Generated by Django 4.1 on 2023-01-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustuser', '0004_alter_transactions_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
