# Generated by Django 4.1 on 2023-01-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='creditCard',
            field=models.CharField(blank=True, default='notapplyed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creditcarddetails',
            name='coustmer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staf.accountdetails'),
        ),
    ]
