# Generated by Django 4.1 on 2023-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0002_accountdetails_creditcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='creditCard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
