# Generated by Django 4.1 on 2023-02-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0003_alter_accountdetails_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcarddetails',
            old_name='coustmer',
            new_name='coustmer1',
        ),
    ]
