# Generated by Django 4.1 on 2023-02-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0004_rename_coustmer_creditcarddetails_coustmer1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcarddetails',
            name='ex_date',
            field=models.DateField(),
        ),
    ]
